2022-03-18 22:47:58,395 DEBUG loging_decos.py Запущено приложение ServerApp,c параметрами ['/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/server.py', 'server.py', '-a', '192.168.0.50', '-p', '8888'] функции gui_flag).
2022-03-18 22:47:58,397 DEBUG loging_decos.py Запущено приложение config_load,c параметрами ['/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/server.py', 'server.py', '-a', '192.168.0.50', '-p', '8888'] функции ServerApp.main().
2022-03-18 22:47:58,397 INFO server.py Запущен сервер, порт для подключений: 8888, адрес с которого принимаются подключения: 192.168.0.50. Если адрес не указан, принимаются соединения с любых адресов.
2022-03-18 22:47:58,397 DEBUG server.py Server launched. IP: 192.168.0.50 Port: 8888
2022-03-18 22:47:58,451 INFO core.py Запущен сервер, порт для подключений: 8888 , адрес с которого принимаются подключения: 192.168.0.50. Если адрес не указан, принимаются соединения с любых адресов.
2022-03-18 22:48:20,145 INFO core.py Установлено соедение с ПК ('192.168.0.50', 58545)
2022-03-18 22:48:20,650 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647632900.159328, 'user': {'account_name': 'TestSender1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlIIAbEuKDWzgLz5hUl+i\n4rNgZTjOb7oDsPpfOJpZwJnc21Z2lIcVf69A+ueV5djiYOJJe7yA6L+74tQZAS8v\nAq/tDWaaTbT83+UiopDBur5ikObJhmi28Iy5qvqI8dRVURYmLh0e9VoKQGO+iLgz\n3Ly6HEkDpqYs/WLtiuVR54fXIJc0UtSrT7aHt2hokwD0oVv0+MAoFt4s2u5O/wMF\nvMQ8KLWJKW5D+aQjvGmteidpQ64vAAB7JwY4JJvNWmyawUySNYbX7hCGDGD7Fhv5\ni4so8fdau/Avu6O2y8GnaNv7PKWO0gGjUPNQaNy39tL/YYDCaDiWlSP6Mx0G3I9M\nowIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-18 22:48:20,650 DEBUG core.py Start auth process for {'account_name': 'TestSender1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlIIAbEuKDWzgLz5hUl+i\n4rNgZTjOb7oDsPpfOJpZwJnc21Z2lIcVf69A+ueV5djiYOJJe7yA6L+74tQZAS8v\nAq/tDWaaTbT83+UiopDBur5ikObJhmi28Iy5qvqI8dRVURYmLh0e9VoKQGO+iLgz\n3Ly6HEkDpqYs/WLtiuVR54fXIJc0UtSrT7aHt2hokwD0oVv0+MAoFt4s2u5O/wMF\nvMQ8KLWJKW5D+aQjvGmteidpQ64vAAB7JwY4JJvNWmyawUySNYbX7hCGDGD7Fhv5\ni4so8fdau/Avu6O2y8GnaNv7PKWO0gGjUPNQaNy39tL/YYDCaDiWlSP6Mx0G3I9M\nowIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-18 22:48:20,658 DEBUG core.py Correct username, starting passwd check.
2022-03-18 22:48:20,661 DEBUG core.py Auth message = {'response': 511, 'bin': '071b3e72e8bf1dcde20a9be5fdf2b54141625782b7307e75e28805c6dd2690832455cc466bfe4124257f2ff88611b8c5252a694ce6f8b4c613f44f1dfb346cce'}
2022-03-18 22:48:21,178 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647632900.6630359, 'account_name': 'TestSender1'}
2022-03-18 22:48:21,684 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647632901.196688, 'user': 'TestSender1'}
2022-03-18 22:48:29,739 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647632908.9893901, 'account_name': 'TestSender1'}
2022-03-18 22:48:34,269 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender1', 'to': 'TestSender1', 'time': 1647632913.3857548, 'mess_text': 'WqrNTmAQineiX8wIP9iQUPwr30CV+CIscsYDbrcQh8OUzRaBKpYMZG6KXr875yXWeSpoQ1CdZWIPFHjDv1UHABd68VyJxOpnrI5xV3OPlo++SnBm2dtkwMQwuUhlbRwRZwqAXszRIF5yQlaOJKYLqrtvWo0iSo+w/sBl3fNpQAipqjXFa3n1UDOj8VOCSs+99hOyJRfhJZMwszmSmcu2ZYjsE9Co5Eyeo5p/+3AytjLouAlshPlCJREvLvFZ18rcSWs/ODCjiyuQ3mypET5Z/nAMrmawBcldeukrIZQhjTmix9pm9zolJbtEfT4xZCvjZkHg+wJGByn3Sc+NLgLWnw=='}
2022-03-18 22:48:34,286 INFO core.py Отправлено сообщение пользователю TestSender1 от пользователя TestSender1.
2022-03-18 22:48:34,787 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/Server/core.py", line 88, in run
    get_message(client_with_message), client_with_message)
  File "/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/common/utils.py", line 19, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
ConnectionResetError: [Errno 54] Connection reset by peer
2022-03-18 22:50:19,609 DEBUG loging_decos.py Запущено приложение ServerApp,c параметрами ['/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/server.py', 'server.py', '-a', '192.168.0.50', '-p', '8888'] функции gui_flag).
2022-03-18 22:50:19,610 DEBUG loging_decos.py Запущено приложение config_load,c параметрами ['/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/server.py', 'server.py', '-a', '192.168.0.50', '-p', '8888'] функции ServerApp.main().
2022-03-18 22:50:19,610 INFO server.py Запущен сервер, порт для подключений: 8888, адрес с которого принимаются подключения: 192.168.0.50. Если адрес не указан, принимаются соединения с любых адресов.
2022-03-18 22:50:19,610 DEBUG server.py Server launched. IP: 192.168.0.50 Port: 8888
2022-03-18 22:50:19,638 INFO core.py Запущен сервер, порт для подключений: 8888 , адрес с которого принимаются подключения: 192.168.0.50. Если адрес не указан, принимаются соединения с любых адресов.
2022-03-18 22:50:28,146 INFO core.py Установлено соедение с ПК ('192.168.0.50', 58552)
2022-03-18 22:50:28,652 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647633028.159625, 'user': {'account_name': 'TestSender2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5gCYYMZBJOBGTby39FrQ\nJWoMLt2d97+Qp9goqQutPQE/kKZWjJYvfAVYcn6SQm2FA1KVR4jo8toQy27q8tee\nh0Srur4sSjtMUv6TMqeSRETlo7LFcVgl0S/RVHHEXAqs2gmFbAGOQRl2UKqksedV\no/o/88mZMNQh+q/Pf9jGgZrid9OI40Un20adJ+fowht35uY+Nthfunz97VoWGqsN\nDsHN21frUJ7LDwvea1i2+clm1TNj03ZkfFDE+BWA/wDmqfkj5EiVroUTYfFehdw/\nuNXxP2BzCNNuVkxm/DO88YMn17ukUDq6KI4tGwXeUARH1DtyuXqcg5ZzGo/fFYep\nxQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-18 22:50:28,653 DEBUG core.py Start auth process for {'account_name': 'TestSender2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5gCYYMZBJOBGTby39FrQ\nJWoMLt2d97+Qp9goqQutPQE/kKZWjJYvfAVYcn6SQm2FA1KVR4jo8toQy27q8tee\nh0Srur4sSjtMUv6TMqeSRETlo7LFcVgl0S/RVHHEXAqs2gmFbAGOQRl2UKqksedV\no/o/88mZMNQh+q/Pf9jGgZrid9OI40Un20adJ+fowht35uY+Nthfunz97VoWGqsN\nDsHN21frUJ7LDwvea1i2+clm1TNj03ZkfFDE+BWA/wDmqfkj5EiVroUTYfFehdw/\nuNXxP2BzCNNuVkxm/DO88YMn17ukUDq6KI4tGwXeUARH1DtyuXqcg5ZzGo/fFYep\nxQIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-18 22:50:28,660 DEBUG core.py Correct username, starting passwd check.
2022-03-18 22:50:28,662 DEBUG core.py Auth message = {'response': 511, 'bin': '9ab89b635100d89989139a2d1130800271c3453d0da95edcdf93bce985099cd84082b250aade6e49bf1438b934dbb11a8f2d87bc54e7702c3fe560afb37007f4'}
2022-03-18 22:50:29,183 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647633028.6636312, 'account_name': 'TestSender2'}
2022-03-18 22:50:29,689 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647633029.202382, 'user': 'TestSender2'}
2022-03-18 22:50:35,225 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1647633035.089725, 'user': 'TestSender2', 'account_name': 'TestSender2'}
2022-03-18 22:50:39,278 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633039.027736, 'account_name': 'TestSender2'}
2022-03-18 22:50:42,301 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender2', 'to': 'TestSender2', 'time': 1647633042.0445929, 'mess_text': 'cAxMVHkoD66umYtwkNMae5BPyV9BLt6FgK+1UHolcaW+PrXAvCo52qCZdiOe5DG5oMiCeppaNQyU950MOzWFGIPiTPJJ4H3iomCWJlpP4K5jh9DcYaJePgtb23sAPHqYzjQALZawgXqJYCLP/a2Dk9z3EySGUBP0cIijfqGOI2CuqwClYy4xSZyKrONClTVezqzvsV8sUjxLMfqV7UezHvtMYIQ8OXTKpCfl2RFP/LwWrzJq0wC2ROuO44m6s9qlI5sL8bU4ZM/HLKoRE9ZytMfFdKM2SrULmp5yxB+KLs/6RUx4OHKSw2PKRWrwJFCgqu5z6uC1TE7Xa00pRr+YXg=='}
2022-03-18 22:50:42,322 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender2.
2022-03-18 22:50:42,825 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/Server/core.py", line 88, in run
    get_message(client_with_message), client_with_message)
  File "/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/common/utils.py", line 19, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
ConnectionResetError: [Errno 54] Connection reset by peer
2022-03-18 22:53:59,031 DEBUG loging_decos.py Запущено приложение ServerApp,c параметрами ['/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/server.py', 'server.py', '-a', '192.168.0.50', '-p', '8888'] функции gui_flag).
2022-03-18 22:53:59,032 DEBUG loging_decos.py Запущено приложение config_load,c параметрами ['/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_6/server.py', 'server.py', '-a', '192.168.0.50', '-p', '8888'] функции ServerApp.main().
2022-03-18 22:53:59,032 INFO server.py Запущен сервер, порт для подключений: 8888, адрес с которого принимаются подключения: 192.168.0.50. Если адрес не указан, принимаются соединения с любых адресов.
2022-03-18 22:53:59,032 DEBUG server.py Server launched. IP: 192.168.0.50 Port: 8888
2022-03-18 22:53:59,068 INFO core.py Запущен сервер, порт для подключений: 8888 , адрес с которого принимаются подключения: 192.168.0.50. Если адрес не указан, принимаются соединения с любых адресов.
2022-03-18 22:54:19,939 INFO core.py Установлено соедение с ПК ('192.168.0.50', 58558)
2022-03-18 22:54:20,441 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647633259.950837, 'user': {'account_name': 'TestSender1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlIIAbEuKDWzgLz5hUl+i\n4rNgZTjOb7oDsPpfOJpZwJnc21Z2lIcVf69A+ueV5djiYOJJe7yA6L+74tQZAS8v\nAq/tDWaaTbT83+UiopDBur5ikObJhmi28Iy5qvqI8dRVURYmLh0e9VoKQGO+iLgz\n3Ly6HEkDpqYs/WLtiuVR54fXIJc0UtSrT7aHt2hokwD0oVv0+MAoFt4s2u5O/wMF\nvMQ8KLWJKW5D+aQjvGmteidpQ64vAAB7JwY4JJvNWmyawUySNYbX7hCGDGD7Fhv5\ni4so8fdau/Avu6O2y8GnaNv7PKWO0gGjUPNQaNy39tL/YYDCaDiWlSP6Mx0G3I9M\nowIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-18 22:54:20,441 DEBUG core.py Start auth process for {'account_name': 'TestSender1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlIIAbEuKDWzgLz5hUl+i\n4rNgZTjOb7oDsPpfOJpZwJnc21Z2lIcVf69A+ueV5djiYOJJe7yA6L+74tQZAS8v\nAq/tDWaaTbT83+UiopDBur5ikObJhmi28Iy5qvqI8dRVURYmLh0e9VoKQGO+iLgz\n3Ly6HEkDpqYs/WLtiuVR54fXIJc0UtSrT7aHt2hokwD0oVv0+MAoFt4s2u5O/wMF\nvMQ8KLWJKW5D+aQjvGmteidpQ64vAAB7JwY4JJvNWmyawUySNYbX7hCGDGD7Fhv5\ni4so8fdau/Avu6O2y8GnaNv7PKWO0gGjUPNQaNy39tL/YYDCaDiWlSP6Mx0G3I9M\nowIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-18 22:54:20,447 DEBUG core.py Correct username, starting passwd check.
2022-03-18 22:54:20,449 DEBUG core.py Auth message = {'response': 511, 'bin': 'a57661ea674eb23f0abefe79766679eea42e39bd6f8c9967b5de67600c6e0055c244baa6c1589eba09fd84d61fa158b447989965c541a5336d36af6aee313465'}
2022-03-18 22:54:20,966 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647633260.4507651, 'account_name': 'TestSender1'}
2022-03-18 22:54:21,470 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647633260.984833, 'user': 'TestSender1'}
2022-03-18 22:54:23,990 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633263.625719, 'account_name': 'TestSender1'}
2022-03-18 22:54:28,013 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender1', 'to': 'TestSender1', 'time': 1647633267.156696, 'mess_text': 'BcPkvnH1f32+MEo0lfnQXEXKvkdWRY4wyN29kgHHrOtsCOCmHWevzmDrVbEMX0d+mFee2vYlFPrAfoSOkNgz6YS6b8hD6g01ELMmAorvv63ZkTDptZpx8hPx40LG+AGGjI/nRuIrTRU8U1cXhwcgnkWfXpIoINdNm3aZ5xSM6DeOudbaWWN5qbBoLTKQjDYRVqOkUfWS2vGWaXhPvIETuwA1At+C8PfLdxhTS+b4Qk7RJeX/M/2T22gqckcc/ck46/J2bbj7b2oMCsVbp4x8Sgki4KY987Ww65s6KBzuaib9YvLK5Xl16otT4u9O+imA/IgVRPT+Yebh1fmibNialw=='}
2022-03-18 22:54:28,030 INFO core.py Отправлено сообщение пользователю TestSender1 от пользователя TestSender1.
2022-03-18 22:54:34,064 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1647633273.9376209, 'user': 'TestSender1', 'account_name': 'TestSender2'}
2022-03-18 23:00:57,044 INFO core.py Установлено соедение с ПК ('192.168.0.50', 59068)
2022-03-18 23:00:57,548 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647633657.055153, 'user': {'account_name': 'TestSender2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5gCYYMZBJOBGTby39FrQ\nJWoMLt2d97+Qp9goqQutPQE/kKZWjJYvfAVYcn6SQm2FA1KVR4jo8toQy27q8tee\nh0Srur4sSjtMUv6TMqeSRETlo7LFcVgl0S/RVHHEXAqs2gmFbAGOQRl2UKqksedV\no/o/88mZMNQh+q/Pf9jGgZrid9OI40Un20adJ+fowht35uY+Nthfunz97VoWGqsN\nDsHN21frUJ7LDwvea1i2+clm1TNj03ZkfFDE+BWA/wDmqfkj5EiVroUTYfFehdw/\nuNXxP2BzCNNuVkxm/DO88YMn17ukUDq6KI4tGwXeUARH1DtyuXqcg5ZzGo/fFYep\nxQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-18 23:00:57,548 DEBUG core.py Start auth process for {'account_name': 'TestSender2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5gCYYMZBJOBGTby39FrQ\nJWoMLt2d97+Qp9goqQutPQE/kKZWjJYvfAVYcn6SQm2FA1KVR4jo8toQy27q8tee\nh0Srur4sSjtMUv6TMqeSRETlo7LFcVgl0S/RVHHEXAqs2gmFbAGOQRl2UKqksedV\no/o/88mZMNQh+q/Pf9jGgZrid9OI40Un20adJ+fowht35uY+Nthfunz97VoWGqsN\nDsHN21frUJ7LDwvea1i2+clm1TNj03ZkfFDE+BWA/wDmqfkj5EiVroUTYfFehdw/\nuNXxP2BzCNNuVkxm/DO88YMn17ukUDq6KI4tGwXeUARH1DtyuXqcg5ZzGo/fFYep\nxQIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-18 23:00:57,552 DEBUG core.py Correct username, starting passwd check.
2022-03-18 23:00:57,553 DEBUG core.py Auth message = {'response': 511, 'bin': '658897cfe03eef992f1f0ca1dd70ee3448fdbe808f791b7bd1816a5b39711e9f8cc99f8abc5aef7333af33ce3fddcbda80a9f8d11a33feda3560bf5a6411aa74'}
2022-03-18 23:00:58,073 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647633657.555159, 'account_name': 'TestSender2'}
2022-03-18 23:00:58,578 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647633658.090948, 'user': 'TestSender2'}
2022-03-18 23:01:02,111 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633661.710847, 'account_name': 'TestSender2'}
2022-03-18 23:01:05,125 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender2', 'to': 'TestSender2', 'time': 1647633664.679816, 'mess_text': 'EaIvkq9gewvw5kG0iDejDDosLexvuvOLm6ztXZKjzQxYfZFWRXkJS7yl4X9pGbMtzTSK+3NCx49FTcugaK/1VQmlWlMvbi6kN+T4oV/a+lN7TZYsy6VinWWD6w5ErBvDUg1W5r8+aIBVPFDUGGxLB049paSKsmbsaWtxJmeE5n2m6zogXPDoJTzafvjNiV3A188Cf3PqOnoNb0mN8+sw5AsGYj5AdcTjrOlsYclL4HC7HjDkih0KPEGzWjdgwSuIW74NtxEG+x2TraWUHi9IlUl+xEXNxBP1P3nGrWfLWAAQh0lB4l8pfN2yj52FRzlUxOCmGmBBGFGW6UDOHJTlaQ=='}
2022-03-18 23:01:05,131 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender2.
2022-03-18 23:01:09,158 DEBUG core.py Разбор сообщения от клиента : {'action': 'add', 'time': 1647633668.622592, 'user': 'TestSender2', 'account_name': 'TestSender1'}
2022-03-18 23:01:11,679 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633671.2146251, 'account_name': 'TestSender1'}
2022-03-18 23:01:14,193 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender2', 'to': 'TestSender1', 'time': 1647633674.12918, 'mess_text': 'OpHXoJb0tpC68O6SbnBGba+Pk8hMLIog9HfqwrHsb1rswmwQT8C98Ussx2cud9oMDI0NtzkTFOn1R4db1sNOUR73sB4DCVbELsS4v0Lkxdcs0tI3MhK20mksKnI45a/1fCvtgDDcbu28ZeCK+HitjO0tHmOf+NRp2heMf2sJ3/ht9JUDa8+QxuiW8QdMR/8f4bBLL96r2PqN52rXGPpywdxdK4BhLcNkPX0DgUczPwPuWTTDyKe609eUh1vD/VTF+SDvtKz06QV97uDDKcjTvGXGMjVi/iiE8DBIBOxkoFti69OUlUVsQnu3mfp7ijmpjeRPZVqCenNGgVDndy/OLQ=='}
2022-03-18 23:01:14,208 INFO core.py Отправлено сообщение пользователю TestSender1 от пользователя TestSender2.
2022-03-18 23:01:19,744 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633679.4023302, 'account_name': 'TestSender2'}
2022-03-18 23:01:25,282 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender1', 'to': 'TestSender2', 'time': 1647633684.8900092, 'mess_text': 'IhkQ0lMM3TYD+lHlht45HjzEz9QgpYiR9NGy8g3vXYJ+VBjk4T0whBiG8q596c5rQF0/v960oQXjVMQMXlt8fUYi9SKfkHMgGZlKbZOJ2jffimydUox12r3AqlcD1zc2k2GoqJvILD1LbI1hI3oZ05qqGAud3jKySnZJdxubYei19xxjr1lIYWadl+8mi8iRAWwu3rMtKRiUX3OFAXK/2nLUKvvdQIGyroDJtspRewtES2sJRQmmkY87nG6S/ml/hmDdDln48C1WbgLiy7sDRip70zF1ZixhxtnY4YjznRBMVosYPzo2yv3FiSo8Fau8Tf8UTKIov3QvfZ8J8uUBoA=='}
2022-03-18 23:01:25,297 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender1.
2022-03-18 23:01:30,319 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender1', 'to': 'TestSender2', 'time': 1647633690.23121, 'mess_text': 'YdCNVHNS3dydu2G3rIIXk4ga+C3sw+7Uat514fRuo67GTBXq4zDTDH6knUgqMzH0dNsfu4XFr/kVepXlsXvJBzZWY83Tk0Dky8IgFKAFIotWlBTPF10xwCwd0VSxWUeYKceZNKLAD9eoBKCEIkVPWkEUVnuTmJFWHAs7xdXQj/37XCtWVmwBCdeZrbCUKiGVxiOVpJEL3QeGXNd/qHDA4oUmD06sWtMUG9C7sSlwvjds+HZhXGv8RKGFeFlynFOXhEILv1fx33nTkoSgbRf08j0gX5KOKxIhzaJnxHaUaVc6qONPz+Gnrzygldvjyvb2hpxlaJBXJtUoMzHX3bRTmw=='}
2022-03-18 23:01:30,325 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender1.
2022-03-18 23:01:35,355 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender2', 'to': 'TestSender1', 'time': 1647633694.3471591, 'mess_text': 'Roo+KNjcp7k3FzIIIzmbPGVaDMVVXBkRj4PiZwjDFSiD0LTCF61HSEqDfmI4DhFDSrclV90olCfdlLiTnP41Eua4JvBityLVq/MxE2ekQLmNGNezrlTfX+t+/Y/xsrCQO+oAFx20eBuJAYGMzH5sBI1rg9IaDZpo4pNz5B/uwiz8DQqkBs/77pMzrpyclzy9ohSFraolvJTjxBYcPLMvBXN7l5OEV+8wrd5gIySKuQMgMwSjYp0fc7rA28/ROnS/u61fD5tGymzV5NsHYHO5PxdSp8Bbzr0AZxjlYpEVnNSL91DR7+klx7VRKIGkgp0zFKnxfShOLdsOxAo2zsoITg=='}
2022-03-18 23:01:35,370 INFO core.py Отправлено сообщение пользователю TestSender1 от пользователя TestSender2.
2022-03-18 23:01:41,404 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender1', 'to': 'TestSender2', 'time': 1647633700.918168, 'mess_text': 'Sp2EghNcQX0CGSgpAGcyk/7dKFZwsjR0tgfpAUzz9H1NTnr212mdYNIDV3TXcMqpponjnLzdVUGgKnF+caF2NqeOT9eAY7siwc1jOr9Np9t2X2Lr+kfj1DE/DXYuZPUTkXmbMXtRsPNJ0fnVBnbFcQyl1auWu1QwoOqBmg+FfAnAU/EXe65rJhhDe7/Byl1/boAcelVuiVCHaIfSg5O13DmQnQF2tc4MTHKMQCV2inIROcVXTeTNTCbDen/PpbkznJd8323EEYoy1mPV/rFwlps1xSgnlPSJRKOnSUL17xyqKFmQ+EeTWvZjeiD/Uv+ptCbHGKl7taYjTtGZH4+1SA=='}
2022-03-18 23:01:41,411 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender1.
2022-03-18 23:01:45,435 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633705.299753, 'account_name': 'TestSender2'}
2022-03-18 23:01:50,966 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633710.739236, 'account_name': 'TestSender1'}
2022-03-18 23:01:52,984 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633712.644681, 'account_name': 'TestSender2'}
2022-03-18 23:01:55,493 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender2', 'to': 'TestSender2', 'time': 1647633715.386254, 'mess_text': 'BIcRYEyfSNMV8sNo1vi4fdGRcibihS1itLtR6sv4xaU7N02ndA3YbAc6jnU5gYPfmK3fN/mEDzWDQ4gx0yXGPOzt8JD0uPscdvjEFqpj7bb0eQCAcJhX0uDFYPKXmEG4xDGlrp3F+q+ZjV2zPfgo9t7xm6vI8ovLW7aqNUMglpifKVeAj1mBg7z7G8bG9nt9GiAKVJW2jX4C273JsrAfMQeO9rPd8jolEcjvTHzL9Lgqy17uREEiUq7tMRDJsJZ0OOVPK6mEeO8FVPUGxD2R4ViprGeg06mt4lhnK0kM6FwlNEa/F4e7h8C7TCdnNe38xGo7eUg8H2E7bQthwcQ8xA=='}
2022-03-18 23:01:55,508 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender2.
2022-03-18 23:01:59,025 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender1', 'to': 'TestSender2', 'time': 1647633718.968844, 'mess_text': '14WeaAgwRqm5cxHgk06L2UDSwmaDjV0fLdVEcO0CQUWDkFEUSOw4MW+8DKBAr4Z/dHpxsXaWOcslebp6jq2liHkVZAy2nSe2++1sG3wZOhdJUfIdUAYmstYogsmfnaq0UKJ/DSXy5+aHA+pnuCwtBRXfPM6wdJPzeECkSqaJpuB9s2J+MVH2Tq6XLTBatSpMaUASk/F+vbzppLULfrw3HAFXnTOVDQfpjKPkusW4dxZgZjumqnIaV2bcAyPmQ2wtd32fFl6AaSRq/LJze87vlXUcLauS1VEetkFZeqX4eNPJmdn/hLAr1nOA0nY7jzFwSPiwuis7cztkXvB5MOUu3A=='}
2022-03-18 23:01:59,040 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender1.
2022-03-18 23:02:02,068 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633721.622904, 'account_name': 'TestSender1'}
2022-03-18 23:02:09,617 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633729.5432682, 'account_name': 'TestSender1'}
2022-03-18 23:02:13,135 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender1', 'to': 'TestSender2', 'time': 1647633733.127889, 'mess_text': 'VUe9SIRVHZ2zb1CVf7aSj8G1TouRr+OYVUbUthimjO7KhNmHVWeGx/EjsXKTtT7KyzK9gGRtwqag+NYq/S4wrHRjEpal5PY5MNUoeyqcaSp8Dm5jjk0z9rzzRgj79ZHUdDldqYS3qYMzRBlTH6vN3ojkKSkhNAmpfgeb0XgQt/QWs6DVMcsbUnmyES4YxfPf+tjKl1PRZSAPiK4YHNBECZyfduhiUHYEDOQnEkc+YYMB6UCMAt+lNgeNoWD7uaYJRAmBi2N019jHLKIiYlEtlgDSXXS7W9NtfJAOvMPFcG3t/9Fu7fDqiY1YuNxiAOQNp2ae5P0TvP9fez4iDZzdsA=='}
2022-03-18 23:02:13,150 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender1.
2022-03-18 23:02:17,179 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633736.748737, 'account_name': 'TestSender2'}
2022-03-18 23:02:20,693 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender1', 'to': 'TestSender2', 'time': 1647633740.289012, 'mess_text': 'ekCfG6k+VZy6/3vlTPEZWyP+awVTUS9v7ugmUz9PjEeXsqlaBuK2DhFTDl0Uz9D0hydSCSeMWa/7kfsja9SowkVNlTHOAJ9K7HedYSx+qXjeXaw4LwBgr1ko3mFt0g5IkXUywN3Hs3sbQv4rpSGvuVoHY+PY81haSnKum3YLwegmsfQARNkXjBxCMK4ysl3D59GtKKgSsS54wVx6EsXTaM6QpJbKxARljq4VDjQyemGb1AO1s6y7Lw6QFVCCgDugfENcIc4Xg3IVSw0HWHDbi8SuqRiUTPeyyKVVKYIRaEBEJs8BsPKiRxAt351R8TGI0GpxeEuH7NLRS3Tonudvfw=='}
2022-03-18 23:02:20,708 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender1.
2022-03-18 23:02:28,261 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647633748.0057092, 'account_name': 'TestSender1'}
2022-03-18 23:02:51,920 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647633771.5755122, 'account_name': 'TestSender2'}
2022-03-18 23:02:51,920 INFO core.py Клиент ('192.168.0.50', 59068) отключился от сервера.
2022-03-18 23:02:53,441 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647633773.082191, 'account_name': 'TestSender1'}
2022-03-18 23:02:53,441 INFO core.py Клиент ('192.168.0.50', 58558) отключился от сервера.
2022-03-18 23:32:07,530 DEBUG loging_decos.py Запущено приложение ServerApp,c параметрами ['/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_7/server.py', 'server.py', '-a', '192.168.0.50', '-p', '8888'] функции gui_flag).
2022-03-18 23:32:07,532 DEBUG loging_decos.py Запущено приложение config_load,c параметрами ['/Users/dmitry/Desktop/Programms/geekbrains/11-PyQT/PyQT_pycharm/Lesson_7/server.py', 'server.py', '-a', '192.168.0.50', '-p', '8888'] функции ServerApp.main().
2022-03-18 23:32:07,533 INFO server.py Запущен сервер, порт для подключений: 8888, адрес с которого принимаются подключения: 192.168.0.50. Если адрес не указан, принимаются соединения с любых адресов.
2022-03-18 23:32:07,533 DEBUG server.py Server launched. IP: 192.168.0.50 Port: 8888
2022-03-18 23:32:07,579 INFO core.py Запущен сервер, порт для подключений: 8888 , адрес с которого принимаются подключения: 192.168.0.50. Если адрес не указан, принимаются соединения с любых адресов.
2022-03-18 23:38:15,906 INFO core.py Установлено соедение с ПК ('192.168.0.50', 59228)
2022-03-18 23:38:16,419 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647635895.923, 'user': {'account_name': 'TestSender2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5gCYYMZBJOBGTby39FrQ\nJWoMLt2d97+Qp9goqQutPQE/kKZWjJYvfAVYcn6SQm2FA1KVR4jo8toQy27q8tee\nh0Srur4sSjtMUv6TMqeSRETlo7LFcVgl0S/RVHHEXAqs2gmFbAGOQRl2UKqksedV\no/o/88mZMNQh+q/Pf9jGgZrid9OI40Un20adJ+fowht35uY+Nthfunz97VoWGqsN\nDsHN21frUJ7LDwvea1i2+clm1TNj03ZkfFDE+BWA/wDmqfkj5EiVroUTYfFehdw/\nuNXxP2BzCNNuVkxm/DO88YMn17ukUDq6KI4tGwXeUARH1DtyuXqcg5ZzGo/fFYep\nxQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-18 23:38:16,419 DEBUG core.py Start auth process for {'account_name': 'TestSender2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5gCYYMZBJOBGTby39FrQ\nJWoMLt2d97+Qp9goqQutPQE/kKZWjJYvfAVYcn6SQm2FA1KVR4jo8toQy27q8tee\nh0Srur4sSjtMUv6TMqeSRETlo7LFcVgl0S/RVHHEXAqs2gmFbAGOQRl2UKqksedV\no/o/88mZMNQh+q/Pf9jGgZrid9OI40Un20adJ+fowht35uY+Nthfunz97VoWGqsN\nDsHN21frUJ7LDwvea1i2+clm1TNj03ZkfFDE+BWA/wDmqfkj5EiVroUTYfFehdw/\nuNXxP2BzCNNuVkxm/DO88YMn17ukUDq6KI4tGwXeUARH1DtyuXqcg5ZzGo/fFYep\nxQIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-18 23:38:16,429 DEBUG core.py Correct username, starting passwd check.
2022-03-18 23:38:16,433 DEBUG core.py Auth message = {'response': 511, 'bin': '152efef3ae5b1ed6a1c83e4da4e3fea2b778b48a890e66d76ec04a048cb81107f8c90a632c4cea215e69ea0d0515d047792091e7c7037d0e0d135120eaaee113'}
2022-03-18 23:38:16,955 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647635896.434888, 'account_name': 'TestSender2'}
2022-03-18 23:38:17,460 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647635896.9651608, 'user': 'TestSender2'}
2022-03-18 23:38:20,984 DEBUG core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647635900.449749, 'account_name': 'TestSender2'}
2022-03-18 23:38:24,503 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender2', 'to': 'TestSender2', 'time': 1647635904.3848488, 'mess_text': 'yurajEdUM0RZGLeDg8rc/697xx8EGFvVdzdmAryVG/NdMqBDRuUV/e6zDY1+IfzDP5FFkyHd/BhEa29lbWFMnv1H4J58yDOkHF20bkuSF/myT6X7i2gXPY98sw7+eEWGVEev/nARBDsyybGl1lgzUyxX+eEtOoT2iYuuHw7qkoyQ3748Yl/jsxCrUNg+QOsloxX3PwiZ9rR/XX8VyKH1PlCq3KxSDRLuG360Odurmp9TaBI9Czy1b38f1zczz7dvz2AqLjYUA76egpnT094LKksgQHU2bkCgDDHrFFE6ts+/8tBIDa2B4F1n17qFtoHfOG72OEwtANYzt5CY9czqfg=='}
2022-03-18 23:38:24,551 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender2.
2022-03-18 23:38:29,587 DEBUG core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'TestSender2', 'to': 'TestSender2', 'time': 1647635908.9510489, 'mess_text': 'MB0nINMKEr/QlmilLRewW0zr4I/Kn8CEM83zlbutGZ4SEsiCU8MGzsrm7NtlNEV8NHi4U0Jiu/ZbWuNoDPGWymjyW0sG1qZs6XJcJzfRFq+OLLhp2QF4F3pc8c/dU6UFX80qyqbAXz1Nx6aIT3dFx4rtWEhjnq35uExswuAlpD1LHf9LcSngcDF0OHAWeNXVjWP3Nquc4NiUjBMVRjLnzfqdiqLLXyRZEe5QAOfL+aEljBQZMftkb1CHJbDGZGm6hO+3UbW2xzchkX7/UyDpcRBHd7G5itJRVX4MSU4vKqZl5FdVraWkc51nERlCu1cW9d53kOr3WDM8s28/8WU2yQ=='}
2022-03-18 23:38:29,602 INFO core.py Отправлено сообщение пользователю TestSender2 от пользователя TestSender2.
2022-03-18 23:38:49,706 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647635929.388754, 'account_name': 'TestSender2'}
2022-03-18 23:38:49,707 INFO core.py Клиент ('192.168.0.50', 59228) отключился от сервера.
